codescene-oss/codescene-vscode

docs/complex-conditional.md
src/download.ts
src/review/model.ts
src/review/review-utils.ts
src/review/reviewer.ts
src/test/suite/review-utils.test.ts

New issue type needs a few tweaks to work properly.

Add complex conditional

---

package.json
src/codescene-interop.ts
src/download.ts
src/review/reviewer.ts

This PR adapts to changes introduced due to changes in the upcoming release of the standalone CodeScene CLI tool

chore: Adapt to newer version of cs binary

---

docs/bumpy-road-ahead-guide.md
docs/complex-conditional-guide.md
docs/complex-method-guide.md
docs/deep-nested-complexity-guide.md

Added new guides which capture a short description of each code smell, its suggested refactoring steps, plus the expected outcome/motivation.

Describe the refactoring steps and wins

---

package.json
src/cs-rest-api.ts
src/executor.ts
src/refactoring/codelens.ts
src/refactoring/cs-refactoring-requests.ts
src/refactoring/refactoring-panel.ts
src/refactoring/refactorings-view.ts
src/webviews/status-view-provider.ts

Updates the CsRefactoringRequests data structure to better suit our needs, and add handling when re-initiating requests for a document or applying a specific refactoring.

Ace view improvements

---

assets/refactor-styles.css
esbuild.js
src/cs-rest-api.ts
src/refactoring/refactoring-panel.ts
src/refactoring/utils.ts
src/test/suite/refactor-utils.test.ts
src/webviews/status-view-provider.ts

Add presentation of review details (if present) to the refactoring recommendation/suggestion or improvement guide. When present they contain coordinates to the code where the issue lies, as well as a short message.
This is to make the manual review step easier, drawing attention to issues in the suggested code.

Review details presentation

---

src/download.ts

This addresses #41, where the processor doesn't support the instruction set used by the downloaded binary.
It will show up as an error popup on extension activation, and also in the new activity bar status view.

fix: Fail extension activation early if binary won't run properly

---

package.json
src/check-rules.ts
src/codescene-interop.ts
src/extension.ts

New approach to debug code health rules in extension.

Added a check rules command to utilize check-rules in CLI

---

package.json
src/code-health-gate/addon.ts
src/code-health-gate/analyser.ts
src/code-health-gate/presentation.ts
src/code-health-gate/tree-model.ts
src/code-health-gate/tree-view.ts
src/documentation/csdoc-provider.ts
src/extension.ts
src/refactoring/commands.ts
src/utils.ts

To further collect usage data we're wrapping some commands that are invoked manually with a telemetry call. This will be used for deciding which direction we should take in further product/feature development.

Additional usage telemetry

---

docs/code-health-gate.md
package.json
src/code-health-gate/addon.ts
src/code-health-gate/analyser.ts
src/code-health-gate/tree-model.ts
src/code-health-gate/tree-view.ts
src/codescene-interop.ts
src/cs-extension-state.ts
src/cs-rest-api.ts
src/cs-statusbar.ts
src/download.ts
src/extension.ts
src/refactoring/addon.ts
src/refactoring/commands.ts
src/refactoring/cs-refactoring-requests.ts
src/review/codelens.ts
src/review/model.ts
src/review/reviewer.ts
src/stats.ts
src/test/suite/stats.test.ts

The code health gate [beta] required a manual refresh to see the difference after code changes.
This PR changes that behaviour using the initial analysis as a baseline, then comparing that to each subsequent code review and updating the code-health-gate view accordingly.

Live delta analysis

---

src/code-health-monitor/analyser.ts
src/code-health-monitor/codelens.ts
src/code-health-monitor/details/view.ts
src/code-health-monitor/model.ts
src/code-health-monitor/tree-model.ts
src/code-health-monitor/tree-view.ts
src/documentation/csdoc-provider.ts
src/documentation/documentation-panel.ts
src/download.ts
src/refactoring/commands.ts
src/review/codelens.ts
src/review/model.ts
src/review/utils.ts
src/status-view/status-view-provider.ts
src/test/suite/refactor-commands.test.ts
src/test/suite/review-utils.test.ts

Fall forward to use the latest version of the devtools binary with the latest API versions.

chore: Update to use latest IDE API

---

src/code-health-monitor/codelens.ts
src/code-health-monitor/tree-model.ts
src/download.ts
src/telemetry.ts
src/test/suite/review-utils.test.ts

* Correcting the function sorting in the code health monitor
* Updating and stabilizing the behaviour of the code health monitor "menu codelens" - subject to further changes
* Update the devtools binary to solve some issues with multiple functions showing in the tree and an issue where files show up even though no degradations are showing

Misc fixes

---

src/code-health-monitor/tree-model.ts
src/code-health-monitor/tree-view.ts
src/download.ts

**NOTE** - an added file with a score < 10 will be counted toward a negative code health impact.

fix(code-health-monitor): Present a grading of total score change in the tree

---

src/code-health-monitor/model.ts
src/code-health-monitor/tree-model.ts
src/code-health-monitor/tree-view.ts

* Clicking ACE summary reveals existing refactorings in tree
* Code health change with percentage details and new icons
* Clean up global summary of score and issues (not obvious if we're counting issues or functions or both)
* Open documentation when clicking file-level issues

feat(code-health-monitor): Misc improvements/polish

---

package.json
src/code-health-monitor/codelens.ts
src/control-center/webview-script.ts
src/cs-extension-state.ts
src/review/codelens.ts

- Remove ACE beta text and enable ACE by default
- Remove previewCodeHealthMonitor setting - always show the monitor

Configuration updates

---

src/codescene-tab/webview-panel.ts
src/codescene-tab/webview/refactoring-components.ts
src/codescene-tab/webview/refactoring-script.ts
src/codescene-tab/webview/refactoring-styles.css
src/refactoring/api.ts
src/refactoring/commands.ts
src/refactoring/request.ts

Update wordings and presentations when LLMs are unable to find a good refactoring.
Includes adding a skipCache flag to the requests that circumvents the cache in order to be able to retry running a certain refactoring

chore(refactoring): Improved user guidance

---

src/code-health-monitor/tree-model.ts

fix(code-health-monitor): Tooltip for code health info should reflect the score change

---

src/codescene-tab/webview-panel.ts

If we're able to refactor, the code will be highlighted again if clicking the fn location component `index.js ... notSoGood [Ln 81]`
Previously, the code to be refactored would be highlighted when a refactoring was found. But if manually deselecting the code there was no way of getting the selection back.

feat(refactoring): Re-select code to be refactored when clicking the function location component

---

src/download.ts
src/review/model.ts
src/review/reviewer.ts
src/review/utils.ts

Fixes the review error when coming across files without any application code.

fix(review): Allow for undefined score meaning "no scorable code"

---

package.json
src/code-health-monitor/analyser.ts
src/code-health-monitor/codelens.ts
src/code-health-monitor/details/styles.css
src/code-health-monitor/details/view.ts
src/code-health-monitor/model.ts
src/code-health-monitor/presentation.ts
src/code-health-monitor/tree-model.ts
src/code-health-monitor/tree-view.ts
src/codescene-tab/webview-panel.ts
src/codescene-tab/webview/components.ts
src/documentation/commands.ts
src/download.ts
src/review/codeaction.ts
src/review/codelens.ts
src/review/reviewer.ts
src/review/utils.ts
src/test/suite/tree-model.test.ts
src/utils.ts

Uses the updated api binary to present improvements and fixed issues in the code health monitor as well as the degradations. Improvements/fixes are sorted lower than the pure degradations
Other UI changes
* A badge/number is added on the file level, indicating how many improvement opportunities there are
* Percentage change is shown on file level to get an indication even if files are collapsed.
* Sorting options - default is sorting all the changed files on ascending score change, showing largest decrease on top

Include improvements in code health monitor

---

src/code-health-monitor/analyser.ts
src/code-health-monitor/model.ts
src/code-health-monitor/tree-model.ts
src/download.ts

Bump `REQUIRED_DEVTOOLS_VERSION` to match as well

chore(binary): Model update: Position->Line

---

package-lock.json
package.json
src/download.ts

- Bump version to 0.9.15
- Add custom binary version validation for Linux x64

chore: Add custom binary for Linux x64

---

.github/workflows/build-and-upload.yml
.github/workflows/github-release.yml
package.json
src/auth/auth-provider.ts
src/code-health-monitor/addon.ts
src/code-health-monitor/background-view.ts
src/code-health-monitor/home/cwf-message-categories.ts
src/code-health-monitor/home/cwf-message-handlers.ts
src/code-health-monitor/home/cwf-parsers.ts
src/code-health-monitor/home/cwf-types.ts
src/code-health-monitor/home/home-html-utils.ts
src/code-health-monitor/home/home-view.ts
src/code-health-monitor/home/types/cwf-feature.ts
src/code-health-monitor/home/types/delta.d.ts
src/code-health-monitor/home/types/index.d.ts
src/code-health-monitor/home/types/messages.d.ts
src/configuration.ts
src/cs-extension-state.ts
src/cs-statusbar.ts
src/extension.ts
src/webview-utils.ts

Replacing the Native CodeHealth Monitor with the Centralized Webview Framework (CWF) version.

feat: CS-5164 Replace Monitor UI
