.gitignore, .vscodeignore, src/download.ts
There were issues when the remote platform was different from the host platform (e.g. linux vs windows). Basically when installing the extension into the remote platform it was copied from the host platform, which could mean an incompatible codescene binary followed along.
There is a remaining issue if you use devcontainers on an m1 mac as it cannot run amd64 binaries. We need to produce actual arm64 binaries to solve it.
=> fix: ensure remote development works

.gitignore, package-lock.json, package.json, src/codescene-interop.ts, src/extension.ts, src/telemetry.ts, src/utils.ts
For CodeScene to be able to improve the VS Code extension, we've added
basic telemetry. Each time the extension is activated, we'll send a
message to devtools.codescene.io.
We're using the official TelemetryLogger interface, which respects
privacy settings and provides information on the VS Code client, like:
- vs-code version
- platform version
- extension version
- vs-code machine id, generated by vs code
The interface is the same that's used by Microsoft's own plugin, see
https://github.com/microsoft/vscode-extension-telemetry/tree/main#common-properties
for more details.
=> Update min vs code version to support TelemetryLogger

src/codescene-interop.ts, src/executor.ts, src/rules-template.ts, src/utils.ts
Before this multiple execution of 'cs review' could be in flight for the same document. But only the latest execution is ever of interest, so it makes no sense to keep the other ones running. This change refactors the execution of external processes so that we can keep this under control.
=> fix: effectivize the execution of the 'cs' process

.github/workflows/test.yml, src/test/suite/extension.test.ts
This is a good basic sanity check because it allows us to test a real activation on windows, macos and linux.
=> test: add basic test checking if activation works

src/executor.ts, src/extension.ts, src/review/reviewer.ts, src/stats.ts, src/telemetry.ts, src/test/suite/stats.test.ts
This will allow us to see which languages are used the most, and also if any of them are in need of being optimized.
=> perf: add execution times by language to telemetry

.gitignore, package-lock.json, package.json, src/auth/auth-provider.ts, src/auth/util.ts, src/configuration.ts, src/coupling/coupling-data-provider.ts, src/coupling/explorer-couplings-view.ts, src/coupling/model.ts, src/coupling/scm-couplings-view.ts, src/cs-rest-api.ts, src/extension.ts, src/git.ts, src/links.ts, src/review/reviewer.ts, src/telemetry.ts, src/test/suite/utils.test.ts, src/utils.ts, src/workspace.ts
This is a work in progress for more advanced CodeScene integration. It adds the ability to log in (either on a free or paid account) and associate your VS code project to a project on the CodeScene server. This enables us to access already performed costly analyses that we can display in the editor. The first release is initially quite basic:
- Login to Cloud
- Fetch change coupling data and display in editor
- Maybe some shortcut commands to access certain pages in the web app 
Check before merge:
=> Authorisation and API access

src/coupling/coupling-data-provider.ts
The Change Coupling presentation currently depends on local git projects being checked out to their default directories - for example `codescene-vscode/`. Since both VSCode workspaces and CodeScene projects can contain multiple git repos, we effectively need to match many-to-many. To keep things fairly simple, we therefore require the repo root names to match.
With this in mind, having a project checked out to a custom directory - either manually or using git worktree - will cause this matching to fail, and no CC data will be presented.
To somewhat remedy this, we implement a simpler code-path for projects/workspace combinations where a clear one-to-one mapping can be made. That is, when there's only one repository in the CodeScene project, and only one git root among
the VSCode workspace …
=> Change Coupling mapping improvement

.gitignore, package-lock.json, src/download.ts, src/telemetry.ts
There's now an aarch64 binary available for the extension to use. This PR changes the download behaviour to check architecture when selecting which binary to get. Using the new binary should enhance performance slightly for users on Mac silicon.
=> Update with darwin amd64 download

src/refactoring/cs-refactoring-requests.ts, src/refactoring/refactoring-panel.ts
To understand how our refactor functionality works, we are adding
minimal telemetry events on the user interactions around that
functionality:
- when a refactoring is attempted by the extension
- when a refactoring is applied by the user
- when the diff is shown by the user
Privacy notes:
- adds a per-request UUID trace-id to the current eventdata in
./src/telemetry.ts - no impact on privacy.
Co-authored-by: Johan Lindbergh <johan.lindbergh@codescene.com>
=> chore: Add a telemetry log to examine refactor usage

README.md, package.json, src/auth/auth-provider.ts, src/extension.ts, src/refactoring/refactorings-view.ts, src/webviews/status-view-provider.ts, src/webviews/status-webview-script.ts, src/workspace.ts
This feature is going to be reworked and might or might not get back into the extension in the future. If it does, it will be in a different form.
Keeping the code functionality for now, but all user facing commands and components are removed.
=> feat!: Remove the Change Coupling feature

src/auth/auth-provider.ts, src/extension.ts, src/telemetry.ts, src/webviews/status-view-provider.ts, src/workspace.ts
Using the userId in the TelemetryLogger allows for a better user experience in our telemetry UI
chore: Use 'session' in place of 'signedIn' in the ExtensionState and make sure that the codescene.isSignedIn context is set (used in package.json for conditionally activating views or commands)
=> Get userId along with name and token from backend for use in Telemetry

package.json, src/auth/auth-provider.ts, src/configuration.ts, src/cs-diagnostics.ts, src/cs-extension-state.ts, src/cs-rest-api.ts, src/extension.ts, src/links.ts, src/refactoring/codeaction.ts, src/refactoring/codelens.ts, src/refactoring/commands.ts, src/refactoring/cs-refactoring-requests.ts, src/refactoring/refactoring-panel.ts, src/refactoring/refactorings-view.ts, src/refactoring/utils.ts, src/utils.ts, src/webviews/status-view-provider.ts, src/workspace.ts
To get around relying on users to reload the extension manually when signing out we're doing a bit of a rewrite to be able to handle consecutive sign in/out calls.
The same goes for checking or unchecking the ACE configuration option, this no longer pops up the "You need to reload CodeScene to enable/disable this feature"
=> fix: Handle signing in/out without having to reload extension

assets/status-view.css, src/coupling/command.ts, src/coupling/coupling-data-provider.ts, src/coupling/scm-couplings-view.ts, src/cs-extension-state.ts, src/cs-rest-api.ts, src/cs-statusbar.ts, src/extension.ts, src/refactoring/codeaction.ts, src/refactoring/codelens.ts, src/refactoring/commands.ts, src/refactoring/cs-refactoring-requests.ts, src/refactoring/refactoring-panel.ts, src/refactoring/refactorings-view.ts, src/refactoring/utils.ts, src/telemetry.ts, src/test/suite/cs-rest-api.test.ts, src/webviews/status-view-provider.ts, src/webviews/status-webview-script.ts
We should not present individual errors for refactoring requests, rather show them in a more general manner.
This PR uses the statusView panel and statusBar item for that. We also include links to the CodeScene Log output for more info, and an option to clear the error state.
=> UX updates in error handling

src/cs-diagnostics.ts, src/cs-extension-state.ts, src/cs-statusbar.ts, src/extension.ts, src/refactoring/refactoring-panel.ts, src/refactoring/refactorings-view.ts, src/review/reviewer.ts, src/webviews/status-view-provider.ts, src/webviews/status-webview-script.ts
As a user of the extension it's sometimes hard to know when to expect to see the code health analysis results, especially when working with larger files where the review can take a bit longer.
Show a loading indication in the status bar item when a review is running. Also, the review state is used to show that a code review is pending in the Auto-refactoring view.
=> UX improvements, present review state

src/codescene-interop.ts, src/refactoring/commands.ts, src/test/suite/refactor-commands.test.ts, src/webviews/status-view-provider.ts
The Large Method code smell is displayed in the vscode extension with details of the actual lines-of-code (LoC) count. This LoC is calculated by the scoring as the active code count - i.e. ignoring comments.
Worth noting is that this count is also used when checking against `function_lines_of_code_warning` in the optional `code-health-rules.json`.
The max-loc-check before requesting a refactoring via ACE is done by just counting the actual lines in the editor. As a user it is hard to understand why for example a function with LoC = 125 - which is below the number reported by the ACE preflight (130) - cannot be refactored.
This PR updates the function info with "active code size" and uses that when comparing against the ACE service preflight response.
=> Fix max-input-loc vs Large Method discrepancy

src/cs-extension-state.ts, src/download.ts, src/extension.ts, src/webviews/status-view-provider.ts
This simplifies the version checking and also enables manual preinstallation of the expected devtools binary.
If download fails, we use the status-view to provide the user with an actionable message explaining how to download and install the binary manually (putting it in the `extensionPath`)
=> Reference a specific devtools binary version

src/code-health-gate/analyser.ts, src/language-support.ts, src/review/reviewer.ts
The `brightscript` and `brighterscript` languageIds are provided by the [RokuCommunity.brightscript](https://marketplace.visualstudio.com/items?itemName=RokuCommunity.brightscript) extension and were not in the original [list of vscode languageIds](https://code.visualstudio.com/docs/languages/identifiers). Because of this, brightscript files were not picked up by our review DocumentSelector.
Fixed by adding the mapping in `language-support.ts`
=> Add Bright[er]Script languageId support

package.json, src/code-health-monitor/addon.ts, src/code-health-monitor/codelens.ts, src/code-health-monitor/tree-model.ts, src/refactoring/cs-refactoring-requests.ts, src/review/codelens.ts, src/review/reviewer.ts
This menu code lens is activated when clicking functions in the code health monitor, showing CodeScene ACE if available, along with code smells affecting this function.
Note - this changes the previous behaviour for showing code smells as code lenses. The review diagnostics are still visible in the regular vscode squiggly line fashion along with showing them in the problems view.
=> feat(codelens): Implement a menu codelens for code health monitor

src/extension.ts, src/review/codeaction.ts
Clicking on 💡 or using the quick fix menu should add actions for explaining code-smells or viewing ACE refactorings if applicable:
=> feat: Add code action for ACE and interactive docs

esbuild.js, package.json, src/auth/auth-provider.ts, src/check-rules.ts, src/code-health-rules/check-rules.ts, src/code-health-rules/index.ts, src/code-health-rules/rules-template.ts, src/coupling/coupling-data-provider.ts, src/cs-rest-api.ts, src/download.ts, src/extension.ts, src/log.ts, src/review/codelens.ts, src/review/reviewer.ts, src/stats.ts, src/telemetry.ts
Chore: Removing the old "CodeScene" output channel and migrate logging to either the "CodeScene Log" output channel.
The "Check Code Health rule match" command result is presented in a modal window instead of the old output channel.
Fix: The StatsCollector was initialized with a `setTimeout` was never disposed, which could possibly cause problems in long-running instances.
This PR also makes sure to not enable any views or commands that depend on the ide binary being fully initialized, which should hopefully get rid of any "Actual command not found, wanted to execute..." messages.
=> Log and startup chores

package.json, src/code-health-monitor/codelens.ts, src/configuration.ts, src/extension.ts, src/review/codelens.ts
After further discussions about the UX we've decided to restore the behaviour of the diagnostics codelenses. Now they're showing by default, and when selecting a decline in the code health monitor we're just adding the refactoring commands if available.
If they're not showing, the code health monitor will add Code Lenses for the introduced issues along with the optional refactoring lenses.
This PR also adds the command "CodeScene: Toggle Review CodeLenses" to make it easier to change the behaviour.
=> chore(codelens): Restore default to showing diagnostics as CodeLenses

src/code-health-monitor/tree-view.ts, src/extension.ts, src/refactoring/addon.ts, src/refactoring/commands.ts, src/refactoring/refactoring-panel.ts, src/refactoring/utils.ts, src/test/suite/refactor-utils.test.ts
When applying a refactoring we want to make sure that that same refactoring isn't still usable.
Make sure to invalidate current refactorings for a file when applying a refactoring.
This is to prevent accidentally applying the same refactoring twice. Instead it makes sense to invalidate and await a new review+delta analysis of the updated file to get the code-health-monitor re-populated with other possible refactoring suggestions.
This commit also moves some of the functionality used by the refactoring panel into the refactoring/commands module.
=> fix(code-health-monitor): Stable handling of multiple subsequent refactorings

LICENSE, package.json, src/control-center/view-provider.ts, src/control-center/webview-script.ts, src/extension.ts, src/terms-conditions.ts
Notification popup for accepting on first use:
Updated control-center-panel:
Command for revoking agreement:
=> feat(terms-and-conditions): Add agreement popup on extension activation

src/cs-statusbar.ts
This happens on startup when no supported file is open. Fix by not implicitly assume analysis is running when state isn't 'idle'.
=> fix(statusbar): Analysis keeps running on startup

esbuild.js, package-lock.json, package.json, src/code-health-monitor/details/view.ts, src/code-health-monitor/details/webview-script.ts, src/codescene-tab/webview/documentation-components.ts, src/codescene-tab/webview/documentation-script.ts, src/codescene-tab/webview/refactoring-components.ts, src/codescene-tab/webview/refactoring-script.ts, src/codescene-tab/webview/utils.ts
The [webview-ui-toolkit will be deprecated](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) at the end of this year. Replace with [VSCode Elements](https://github.com/vscode-elements/elements).
=> chore(web-ui): Remove @vscode/webview-ui-toolkit dependency

src/codescene-tab/webview-panel.ts, src/codescene-tab/webview/ace-acknowledgement-styles.css, src/codescene-tab/webview/styles.css, src/codescene-tab/webview/utils.ts, src/refactoring/commands.ts
Add some details about common security concerns
This commit also customizes some of the common styles used by the codescene-tab. Previously those styles were inherited from the markdown.css stylesheet
=> chore(refactoring): Adjust and clarify ACE acknowledgement banner

src/code-health-monitor/details/styles.css, src/code-health-monitor/details/view.ts, src/code-health-monitor/details/webview-script.ts, src/code-health-monitor/tree-model.ts, src/codescene-tab/webview/refactoring-components.ts
Updating with latest sketches.
Getting the seti-icons with correct coloring is not trivial, leaving that for now.
Also, the [vscode-element](https://github.com/vscode-elements/elements) button is not designed to be able to stretch, so keeping that in the standard look for now.
=> chore(code-health-monitor): ch monitor and details-view UX updates

src/codescene-tab/webview/refactoring-components.ts, src/test/suite/refactoring-components.test.ts
When getting a refactoring with no `reasons-with-details` (i.e. probably a high/full confidence refactoring), the (folded) “**Refactoring notes**” would show a text about LLMs not finding a suitable refactoring if unfolded.
Solved by skipping the colllapsible header altogether if no reasons are supplied in the service response.
=> fix(refactoring-panel): Correctly present refactoring reasons

src/codescene-tab/webview-panel.ts, src/codescene-tab/webview/components.ts, src/codescene-tab/webview/documentation-script.ts, src/codescene-tab/webview/refactoring-components.ts, src/codescene-tab/webview/refactoring-script.ts, src/codescene-tab/webview/refactoring-styles.css, src/codescene-tab/webview/styles.css
If the side panel is open with either a code smell documentation or a refactoring we'll present a warning message on certain code changes. The current condition is when the user makes edits _in_ or _above_ the function considered in the panel.
=> fix(refactoring/documentation): Add file-changes message when applicable

src/auth/auth-provider.ts, src/code-health-monitor/addon.ts, src/code-health-monitor/analyser.ts, src/code-health-monitor/codelens.ts, src/code-health-monitor/details/view.ts, src/code-health-monitor/tree-model.ts, src/code-health-monitor/tree-view.ts, src/code-health-rules/index.ts, src/codescene-tab/webview-panel.ts, src/codescene-tab/webview/refactoring-components.ts, src/control-center/view-provider.ts, src/documentation/commands.ts, src/extension.ts, src/refactoring/api.ts, src/refactoring/commands.ts, src/refactoring/model.ts, src/refactoring/request.ts, src/review/codeaction.ts, src/review/codelens.ts, src/stats.ts, src/telemetry.ts, src/terms-conditions.ts, src/test/suite/refactor-utils.test.ts, src/test/suite/refactoring-components.test.ts, src/utils.ts
After discussion with Product, we're doing an overhaul of the user telemetry in order to be able to find a good market fit.
Some notes: 
* Replace the extensionId prefix that's automatically added by the TelemetrySender in order to keep event name length down
* Remove all command/ events - we're only interested in actual user actions
* When sending telemetry from a command, we make sure to add a "source" property
=> Telemetry event overview

src/control-center/view-provider.ts, src/cs-extension-state.ts, src/extension.ts, src/refactoring/addon.ts, src/telemetry.ts, src/terms-conditions.ts
When using async/await in the `activate` function, the control-center panel `resolveWebviewView` never gets called until the binary download and T&C acceptance is done. So the only way for a user to get feedback is through the statusbar-item.
Changing this back to promise-based lets the control-center resolve immediately, letting it be displayed during the download and T&C accept procedures. This makes it much clearer as to what's going on in startup, which is particularly important while downloading on slow connections.
The startup changes also causes some telemetry-event changes
* `control-center/visibility` is run immediately after `on_activate_extension`
* Add `on_activate_extension_error` event (and keep moving towards snake_case)
=> Ensure control-center is resolved while initializing

src/extension.ts, src/review/reviewer.ts
Uses `fileSystemWatcher` to detect deletions both inside and outside the editor and make sure that delta analysis results are cleared for the deleted/renamed/moved files.
=> fix(code-health-monitor): Respect file delete/rename/move

src/codescene-tab/webview-panel.ts
When content above has been changed, but the function content remains valid we need to update the function to refactor range. If we don't, we will apply/replace the refactored function at the wrong location.
=> fix(refactoring): Keep function range updated

src/control-center/view-provider.ts, src/control-center/webview-script.ts, src/extension.ts, src/refactoring/addon.ts
When ACE fails to initialize due to for example a connection error - this PR adds a simple albeit a quite secret way to retry initialization by just clicking on the `error` badge.
The plan is to refine the UX later on, but with this we can use the `codescene.ace.activate` command introduced in the PR to retry regardless of UX.
=> Retry ACE connection on fail

src/code-health-monitor/addon.ts, src/code-health-monitor/codelens.ts, src/code-health-monitor/tree-model.ts, src/code-health-monitor/tree-view.ts
When a function is selected in the code health monitor and shown in the details view, it's not properly updated even if the function presented has been improved/degraded in any way.
Make sure that the content of the details view is updated regardless of the old tree-view selection.
=> Bugfix: Refresh code health details on updates

src/code-health-monitor/details/view.ts, src/codescene-tab/webview/components.ts
Unfortunately there seems to be no way of tapping into the vscode icon-theme and presenting the same filename icon as is done in the native tree-views. See https://github.com/microsoft/vscode/issues/183893
Let's not try to hack around it by adding hard-coded icons or using haxx like this either https://stackoverflow.com/questions/66178468/vscode-api-how-to-get-icons-from-file-icon-theme
=> chore: Add a file-icon along the filename in refactor and details view

src/language-support.ts, src/refactoring/addon.ts, src/refactoring/capabilities.ts, src/test/suite/refactoring-capabilities.test.ts
Instead of translating extensions supported by the analysis lib into vscode languageIds and checking against that - we're matching directly on an extension pattern (**/*.ext)
This keeps us from having mismatches with for example `.edn` files being detected as 'clojure' and sent for review.
=> fix(language-support): Make sure review and refactoring DocumentMatchers are in sync with the analysis lib

src/code-health-monitor/model.ts, src/code-health-monitor/tree-model.ts, src/download.ts, src/review/utils.ts, src/utils.ts
No score (review or delta) should be rounded on the client - We should only use what's provided by the analysis api/binary. Bump in `download.ts` to use new binary with corrected presentation code.
=> fix: Score rounding issues

src/download.ts, src/refactoring/capabilities.ts, src/review/model.ts, src/review/utils.ts, src/test/suite/refactoring-capabilities.test.ts, src/test/suite/review-utils.test.ts
* removes expression-level-code-smells (included as file-level instead)
* Use 1-indexed columns from the enclosingFn call
=> chore(binary): Adapt to new devtools binary

src/code-health-monitor/presentation.ts
* Display 99 if number of issues is 100 and over
=> fix(code-health-monitor): No badge if >99 issues in code health monitor
